MEAN=0
STD=1

BATCH_SIZE=4
WORKERS=2
DATA_DIR = "/media/liasorin/T9/SonarSweep_dataset_combined/vfov12hfov60"

TRAIN_NEW = True

 
ALPHA = 45  # in degrees
FACTOR = 1.05
N_LABEL = 48      
MINDEPTH = 0.5
MAXDEPTH = 5.0  


CAM_RESOLUTION_WIDTH_FOR_IMAGE_FEATURE_EXTRACTION = 368 # for 60 degree
CAM_RESOLUTION_HEIGHT_FOR_IMAGE_FEATURE_EXTRACTION = 68 # for 12 degree

SONAR_RESOLUTION_WIDTH_FOR_IMAGE_FEATURE_EXTRACTION = 150 # pixel for 60 degree
SONAR_RESOLUTION_HEIGHT_FOR_IMAGE_FEATURE_EXTRACTION = 1000 # pixel for 5 meters